### ISSUE TITLE
append analysis to a c3d already processed with Nexus

### ISSUE THREAD

**Issue by aaa34169** [OpenMA/openma#18]
i want to add openMA time sequence to a c3d aleready including vicon model outputs 

The attached code works fine. But Mokka fails to open it. 
If i remove all model outputs from my gait c3d, then i can open it in Mokka. 

[codeC3ds.zip](https://github.com/OpenMA/openma/files/482325/codeC3ds.zip)

**Comment by Alzathar** [comment]
There is several problems in this issue.

# Main Problem

## Explanation

The main problem is related to the fact that the C3D format is limited to one unit per point type. When you extract joint kinetics with the function `ma.body.extract_joint_kinetics`, the results are normalized by the mass of the subject. Thus, the unit of computed forces and moments is "N/kg" and "Nmm/kg", respectively. However, Nexus set in your C3D these units as "N" and "Nmm". So the existing forces and moments have the unit "N" and "Nmm" (even if most of them correspond to normalized forces and moments). When you export the data to the C3D format, the C3D handler looks for incompatible unit. If for the same point type, different units are found, the handler sends an error message to the logger and stops. If you look for the result of the function `ma.io.write`, it should be `False`.

## Quick way to fix

The quickest way to fix your problem is to set the unit to "N", "Nmm", and "W" for the `ma.TimeSequence` objects with the type `ma.TimeSequence.Type_Force`, `ma.TimeSequence.Type_Moment`, and `ma.TimeSequence.Type_Power` respectively.

# Other problems

As wrote above, the C3D handler detect an error, sends a message to the logger and stops. The problem with the Python bindings is that:
- No error message is displayed (the logger is set to mute by default in the bindings)
- No fail is detected by Python (i.e. the script is not stopped)
- The file was created but the content is empty.

# Actions to perform
- [x] Improve the bindings to catch error messages and trigger an exception
- [x] Delete the file newly created in case of failure.

**Comment by Alzathar** [comment]
Your script will now trigger an exception in Python and no empty file will remain. The problem with the units is still here, but that's an excepted behaviour. If you want to discuss about this point, please open a new issue.
